# Site
name: 'HNK'
description: 'HNK - Nhận Đặt, Mua Hàng Nhật Nội Địa'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'HNK-Order Hàng Nhật Nội Địa'
email: 'hangnhat.noidia.hnk@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hoank:
      name:           Hoa Nguyen
      url:            hoank
      site:           https://www.facebook.com/khachoa.nguyen.93
      avatar:         assets/images/avatar1.jpg
      bio:            "Chào bạn, mình là Hòa. Đang sống và làm việc tại Osaka, Nhật Bản. Hiện tại mình đang làm về mảng Web application. Chúc bạn một ngày vui vẻ!!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      facebook:       https://www.facebook.com/khachoa.nguyen.93
      youtube:       https://www.youtube.com/channel/UCI_-Z5Op_pT5jCvOoWbNCeQ

    van:
      name:           Van Hoang
      url:            van
      site:           https://www.facebook.com/hoangngoc.van99
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      facebook:       https://www.facebook.com/hoangngoc.van99
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hoank
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]